networks:
  proxy-network:
    external: true

services:
  vd:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vd
    restart: unless-stopped
    volumes:
      - ./app:/app/app
    env_file:
      - .env
    environment:
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    networks:
      - proxy-network
