from fastapi import FastAPI, HTTPException
from fastapi.responses import StreamingResponse
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel
import requests
import yt_dlp
import os
import hashlib
import json
import time

import shutil

app = FastAPI()

CACHE_DIR = "app/cache"
os.makedirs(CACHE_DIR, exist_ok=True)
CACHE_EXPIRY = 3600 # 1 hora de validade, pois links do YT/FB perdem a validade!

class URLRequest(BaseModel):
    url: str

class CookieRequest(BaseModel):
    content: str
    password: str

class VerifyRequest(BaseModel):
    password: str

@app.post("/api/admin/verify")
def verify_admin(request: VerifyRequest):
    admin_pass = os.getenv("ADMIN_PASSWORD", "admin")
    if request.password == admin_pass:
        return {"status": "ok"}
    raise HTTPException(status_code=401, detail="Senha incorreta.")

@app.post("/api/admin/update_cookies")
def update_cookies(request: CookieRequest):
    admin_pass = os.getenv("ADMIN_PASSWORD", "admin")
    if request.password != admin_pass:
         raise HTTPException(status_code=401, detail="Não autorizado. Senha incorreta.")

    content = request.content.strip()
    # Verificação básica de formato
    if not ".facebook.com" in content and not ".youtube.com" in content and not ".x.com" in content and not ".instagram.com" in content:
        if not content.startswith("# Netscape"):
            raise HTTPException(status_code=400, detail="Formato de cookie inválido ou domínio não suportado.")

    try:
        cookie_path = 'app/cookies.txt'
        
        # 1. Identificar domínios no novo conteúdo
        new_domains = set()
        new_valid_lines = []
        for line in content.splitlines():
            l = line.strip()
            if not l or l.startswith("#"):
                continue
            parts = l.split("\t")
            if len(parts) >= 1:
                new_domains.add(parts[0])
                new_valid_lines.append(l)

        if not new_valid_lines:
            raise HTTPException(status_code=400, detail="Nenhum cookie válido encontrado no conteúdo enviado.")

        # 2. Ler cookies existentes e filtrar os que NÃO estão nos novos domínios
        existing_lines = []
        if os.path.exists(cookie_path):
            with open(cookie_path, 'r', encoding='utf-8') as f:
                for line in f:
                    l = line.strip()
                    if not l or l.startswith("#"):
                        continue
                    parts = l.split("\t")
                    if len(parts) >= 1 and parts[0] not in new_domains:
                        existing_lines.append(l)

        # 3. Combinar: Cabeçalho + Cookies preservados + Novos cookies
        final_lines = [
            "# Netscape HTTP Cookie File",
            "# This file is automatically generated and merged by the VD app. Do not edit.",
            ""
        ]
        final_lines.extend(existing_lines)
        final_lines.extend(new_valid_lines)

        # Salva no arquivo
        with open(cookie_path, 'w', encoding='utf-8') as f:
            f.write("\n".join(final_lines) + "\n")

        # Limpa o cache automaticamente para forçar o uso dos novos cookies
        if os.path.exists(CACHE_DIR):
            shutil.rmtree(CACHE_DIR)
            os.makedirs(CACHE_DIR, exist_ok=True)

        merged_domains = ", ".join(list(new_domains))
        return {"message": f"Cookies para {merged_domains} atualizados com sucesso! Outros domínios preservados."}
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Erro ao processar cookies: {str(e)}")

@app.post("/api/info")
def get_video_info(request: URLRequest):
    # Verificação de Cache
    url_hash = hashlib.md5(request.url.encode('utf-8')).hexdigest()
    cache_path = os.path.join(CACHE_DIR, f"{url_hash}.json")
    
    if os.path.exists(cache_path):
        if time.time() - os.path.getmtime(cache_path) < CACHE_EXPIRY:
            try:
                with open(cache_path, 'r', encoding='utf-8') as f:
                    return json.load(f)
            except Exception:
                pass

    ydl_opts = {
        'format': 'best', 
        'quiet': True,
        'no_warnings': True,
        'extract_flat': False,
        'extractor_args': {
            'youtube': {
                'player_client': ['android', 'ios', 'web'],
                'include_dash_manifest': [False],
                'include_hls_manifest': [False],
            }
        },
        'http_headers': {
            'User-Agent': 'Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Mobile Safari/537.36',
            'Accept-Language': 'pt-BR,pt;q=0.9,en;q=0.8',
        }
    }
    
    # Suporte para baixar vídeos privados usando cookies do navegador
    cookie_path = 'app/cookies.txt'
    if os.path.exists(cookie_path) and os.path.getsize(cookie_path) > 200:
        ydl_opts['cookiefile'] = cookie_path
        # Mantém Referer se houver cookies
        ydl_opts['http_headers']['Referer'] = 'https://www.youtube.com/'
        
    try:
        with yt_dlp.YoutubeDL(ydl_opts) as ydl:
            info_dict = ydl.extract_info(request.url, download=False)
            
            if 'entries' in info_dict:
                info_dict = info_dict['entries'][0]

            formats_list = []
            if 'formats' in info_dict:
                for f in info_dict['formats']:
                    vcodec = str(f.get('vcodec', '')).lower()
                    acodec = str(f.get('acodec', '')).lower()
                    ext = str(f.get('ext', '')).lower()
                    
                    # O yt-dlp define como 'none' explícito quando não há a trilha correspondente (vídeos DASH soltos)
                    is_video_only = (vcodec != 'none' and vcodec != '') and (acodec == 'none')
                    is_audio_only = (vcodec == 'none') and (acodec != 'none' and acodec != '')
                    
                    # Filtra arquivos que sejam apenas áudio ou apenas vídeo, mas aceita os indefinidos (Facebook sd/hd)
                    if not is_video_only and not is_audio_only and ext in ['mp4', 'webm']:
                        height = f.get('height') or 0
                        res = f.get('resolution') or f.get('format_id') or f.get('format') or 'Padrão'
                        
                        if 'audio' in str(res).lower():
                            continue
                        
                        # Transforma 'sd' e 'hd' para maiúsculas ('SD', 'HD')
                        res_str = str(res)
                        if res_str.lower() in ['sd', 'hd']:
                            res_str = res_str.upper()
                            
                        res_label = res_str
                        if f.get('format_note') and res_str.lower() not in str(f.get('format_note')).lower():
                            res_label += f" ({f.get('format_note')})"
                            
                        formats_list.append({
                            'url': f.get('url'),
                            'resolution': res_label.strip(),
                            'height': int(height)
                        })
                            
            # Filtra duplicados pela resolução, mantendo o mais recente da iteração
            unique_formats = {}
            for f in formats_list:
                unique_formats[f['resolution']] = f
                
            sorted_formats = sorted(list(unique_formats.values()), key=lambda x: x['height'], reverse=True)

            result = {
                "title": info_dict.get('title', 'Vídeo'),
                "id": info_dict.get('id', 'video'),
                "thumbnail": info_dict.get('thumbnail'),
                "duration": info_dict.get('duration'),
                "url": info_dict.get('url'),
                "extractor": info_dict.get('extractor'),
                "formats": sorted_formats
            }
            
            # Grava no cache
            try:
                with open(cache_path, 'w', encoding='utf-8') as f:
                    json.dump(result, f, ensure_ascii=False)
            except:
                pass

            return result
    except Exception as e:
        erro = str(e).lower()

        if "login required" in erro or "cookies" in erro or "not logged in" in erro:
            raise HTTPException(
                status_code=401,
                detail="Este vídeo requer login. Cookies inválidos ou expirados."
            )

        if "private" in erro or "permission" in erro:
            raise HTTPException(
                status_code=403,
                detail="Vídeo privado ou sem permissão de acesso."
            )

        raise HTTPException(status_code=400, detail=str(e))

@app.get("/api/download")
def proxy_download(url: str, title: str = "video"):
    try:
        req_headers = {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
        }
        
        # Abriremos a requisição com stream=True. 
        # O requests avalia apenas os cabeçalhos sem jogar o vídeo inteiro na RAM!
        response = requests.get(url, headers=req_headers, stream=True)
        response.raise_for_status()
        
        def iterfile():
            with response:
                # Usa pacotes maiores (1MB) para streaming extremamente eficiente
                for chunk in response.iter_content(chunk_size=1024 * 1024):
                    if chunk:
                        yield chunk
                    
        headers = {
            'Content-Disposition': f'attachment; filename="{title}.mp4"'
        }
        
        content_type = response.headers.get('Content-Type', 'video/mp4')
        return StreamingResponse(iterfile(), media_type=content_type, headers=headers)
        
    except Exception as e:
        raise HTTPException(status_code=400, detail=f"Erro no download proxy: {str(e)}")

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
STATIC_DIR = os.path.join(BASE_DIR, "static")
os.makedirs(STATIC_DIR, exist_ok=True)
app.mount("/", StaticFiles(directory=STATIC_DIR, html=True), name="static")
